import type { Metadata } from "next";
import CategoryBar from "@/components/CategoryBar";
import { getMainSubCategory } from "@/services/category";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const mainCategory = await getMainSubCategory();
  return (
    <>
      <div className="flex py">
        <CategoryBar mainCategory={mainCategory} isAdmin={true} />
      </div>
      {children}
    </>
  );
}
