import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";
import type { Session } from "@/types/user";
import CategoryBar from "@/components/CategoryBar";
import { getMainSubCategory } from "@/services/category";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await getServerSession(); // Fetch session data on the server side
  const mainCategory = await getMainSubCategory();
  return (
    <>
      <div className="flex py-1 bg-slate-300">
        <CategoryBar mainCategory={mainCategory} isAdmin={true} />
      </div>
      {children}
    </>
  );
}
