import type { Metadata } from "next";
import "../globals.css";
import NavBar from "@/components/NavBar";
import { getServerSession } from "next-auth/next";
import type { Session } from "@/types/user";
import AdminPageSelect from "@/components/AdminPageSelect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await getServerSession(); // Fetch session data on the server side

  return (
    <>
      <div className="A1">
        <NavBar session={session} isAdmin={true} />
      </div>
      <div className="A2 flex">
        <div className="B1 h-min-screen bg-[#FAFAF7] border-r">
          <AdminPageSelect />
        </div>
        <div className="B2 flex-1 bg-[#FAFAF7]">{children}</div>
      </div>
    </>
  );
}
