import type { Metadata } from "next";
import "../globals.css";
import NavBar from "@/components/NavBar";
import { getServerSession } from "next-auth/next";
import type { Session } from "@/types/user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await getServerSession(); // Fetch session data on the server side

  return (
    <>
      <NavBar session={session} isAdmin={true} />
      {children}
    </>
  );
}
