const keyboardSeed = [
  {
    name: "Logitech G Pro X 60 Lightspeed",
    price: 14995,
    stock: 18,
    description:
      "A compact 60% gaming keyboard built for competitive play, combining wireless Lightspeed connectivity with programmable controls and customizable RGB lighting.",
    filters: {
      layout: "ANSI",
      connectivity: "Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "60%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "65 hours",
      hotSwappable: "Yes",
      switchName: "GX Optical",
      keycaps: "PBT",
      software: "Logitech G Hub",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl:
      "https://www.games.rs/files/thumbs/files/images/product/thumbs_800/Tastatura-Logitech-G-PRO-X-60-Lightspeed-cena-prodaja-Srbija-HTA00349-2_800_1000px.jpg",
  },
  {
    name: "Razer Huntsman V3 Pro Mini",
    price: 17999,
    stock: 12,
    description:
      "A 60% competitive gaming keyboard featuring adjustable actuation and rapid-trigger technology for highly responsive movement and precise inputs.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Optical",
      rgb: "Yes",
      keyboardSize: "60%",
    },
    attributes: {
      actuationPoint: "0.1-4.0 mm",
      pollingRate: "8000 Hz",
      switchName: "Razer Analog Optical",
      keycaps: "PBT",
      software: "Razer Synapse",
      onboardMemory: "Yes",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl: "https://m.media-amazon.com/images/I/71h9WW-ew-L._AC_SL1500_.jpg",
  },
  {
    name: "SteelSeries Apex Pro TKL Wireless Gen 3",
    price: 24999,
    stock: 9,
    description:
      "A premium tenkeyless gaming keyboard with adjustable OmniPoint switches, wireless connectivity, and extensive per-key customization.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Magnetic",
      rgb: "Yes",
      keyboardSize: "80% / TKL",
    },
    attributes: {
      actuationPoint: "0.1–4.0 mm",
      pollingRate: "8000 Hz",
      batteryLife: "40+ hours",
      switchName: "OmniPoint 3.0",
      keycaps: "PBT",
      software: "SteelSeries GG",
      onboardMemory: "Yes",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://images.ctfassets.net/8y9xq8f2g9f3/steelseries-apex-pro-tkl-gen-3.jpg",
  },
  {
    name: "Keychron Q1 Max",
    price: 18999,
    stock: 21,
    description:
      "A customizable 75% mechanical keyboard with a sturdy aluminum chassis, hot-swappable switches, and multi-mode wireless connectivity.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "75%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 180 hours",
      hotSwappable: "Yes",
      switchName: "Gateron Jupiter Red",
      keycaps: "KSA PBT",
      mountingStyle: "Gasket Mount",
      plateMaterial: "Steel",
      caseMaterial: "Aluminum",
      connection: "2.4 GHz / Bluetooth / USB-C",
      software: "Keychron Launcher",
      nKeyRollover: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0059/0630/1017/files/Q1_Max_Carbon_Black_1.jpg",
  },
  {
    name: "Wooting 80HE",
    price: 23999,
    stock: 7,
    description:
      "A high-performance 80% gaming keyboard built around Hall-effect switches, offering adjustable actuation and rapid-trigger functionality.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Magnetic",
      rgb: "Yes",
      keyboardSize: "80% / TKL",
    },
    attributes: {
      actuationPoint: "0.1–4.0 mm",
      pollingRate: "8000 Hz",
      hotSwappable: "Yes",
      switchName: "Lekker L60",
      switchForce: "60 cN",
      mountingStyle: "Gasket Mount",
      keycaps: "PBT",
      software: "Wootility",
      onboardMemory: "Yes",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl:
      "https://www.inpad.com.tw/data/goods/gallery/202506/1750239767392018849.jpg",
  },
  {
    name: "Corsair K70 Max RGB",
    price: 20999,
    stock: 15,
    description:
      "A full-featured TKL-style gaming keyboard with magnetic Hall-effect switches, adjustable actuation, and a premium aluminum frame.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Magnetic",
      rgb: "Yes",
      keyboardSize: "80% / TKL",
    },
    attributes: {
      actuationPoint: "0.4–3.6 mm",
      pollingRate: "8000 Hz",
      switchName: "MGX Magnetic",
      switchForce: "45 g",
      keycaps: "PBT Double-Shot",
      caseMaterial: "Aluminum",
      plateMaterial: "Steel",
      software: "Corsair iCUE",
      onboardMemory: "Yes",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl: "https://www.komplett.dk/img/p/800/1251281_2.jpg",
  },
  {
    name: "ASUS ROG Azoth",
    price: 19999,
    stock: 11,
    description:
      "A premium 75% mechanical keyboard designed for gaming and customization, featuring hot-swappable switches, wireless connectivity, and a built-in OLED display.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "75%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 2000 hours",
      hotSwappable: "Yes",
      switchName: "ROG NX Red",
      switchForce: "45 g",
      keycaps: "PBT",
      mountingStyle: "Gasket Mount",
      caseMaterial: "Aluminum",
      connection: "2.4 GHz / Bluetooth / USB-C",
      software: "Armoury Crate",
      onboardMemory: "Yes",
      nKeyRollover: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://dlcdnwebimgs.asus.com/gain/0E5A9B8E-0A2C-4D5A-BF5B-ROG-AZOTH.jpg",
  },
  {
    name: "Glorious GMMK 2 65%",
    price: 8999,
    stock: 26,
    description:
      "A compact 65% mechanical keyboard with a hot-swappable design, aluminum top frame, and extensive RGB customization.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "65%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      hotSwappable: "Yes",
      switchName: "Glorious Fox Linear",
      keycaps: "ABS",
      caseMaterial: "Aluminum",
      plateMaterial: "Steel",
      software: "Glorious CORE",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl:
      "https://www.king-games.co.il/files/products/product30139_image2_2024-12-01_14-49-46.webp",
  },
  {
    name: "NuPhy Halo75 V2",
    price: 13999,
    stock: 19,
    description:
      "A stylish 75% mechanical keyboard combining a compact layout with wireless connectivity, hot-swappable switches, and vibrant RGB lighting.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "75%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 120 hours",
      hotSwappable: "Yes",
      switchName: "NuPhy Mint",
      keycaps: "PBT",
      mountingStyle: "Gasket Mount",
      connection: "2.4 GHz / Bluetooth / USB-C",
      software: "NuPhyIO",
      nKeyRollover: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0268/7299/1397/files/halo75-v2-black.jpg",
  },
  {
    name: "Akko 5075B Plus",
    price: 8999,
    stock: 32,
    description:
      "A versatile 75% mechanical keyboard with tri-mode connectivity, hot-swappable switches, and a gasket-mounted construction aimed at a smooth typing experience.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "75%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 120 hours",
      hotSwappable: "Yes",
      switchName: "Akko Cream Yellow",
      keycaps: "PBT",
      mountingStyle: "Gasket Mount",
      caseMaterial: "Plastic",
      connection: "2.4 GHz / Bluetooth / USB-C",
      software: "Akko Cloud Driver",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0599/2207/9704/files/5075b-plus-black-silver.jpg",
  },
  {
    name: "MonsGeek M1W",
    price: 11999,
    stock: 17,
    description:
      "A premium aluminum 75% keyboard offering tri-mode connectivity, hot-swappable switches, and a gasket-mounted internal structure.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "75%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 500 hours",
      hotSwappable: "Yes",
      switchName: "Akko Cream Yellow",
      keycaps: "PBT",
      mountingStyle: "Gasket Mount",
      caseMaterial: "Aluminum",
      plateMaterial: "PC",
      connection: "2.4 GHz / Bluetooth / USB-C",
      software: "MonsGeek Driver",
      nKeyRollover: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0604/3207/9891/files/M1W-SP-Black.jpg",
  },
  {
    name: "Ducky One 3 TKL",
    price: 10499,
    stock: 13,
    description:
      "A dependable tenkeyless mechanical keyboard with a classic layout, hot-swappable switches, and bright per-key RGB illumination.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Tactile",
      rgb: "Yes",
      keyboardSize: "80% / TKL",
    },
    attributes: {
      hotSwappable: "Yes",
      switchName: "Cherry MX Brown",
      switchForce: "55 cN",
      keycaps: "PBT Double-Shot",
      plateMaterial: "Steel",
      connection: "USB-C",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      onboardMemory: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://4frag.ru/image/cache/data/Klaviatury/Ducky/One%203%20TKL/ducky-one-3-tkl-rgb-black-cherry-mx-black-switch-ru-layout-2-1000x1000.jpg",
  },
  {
    name: "HyperX Alloy Origins 65",
    price: 8499,
    stock: 24,
    description:
      "A compact 65% gaming keyboard with a durable aluminum body, HyperX mechanical switches, and bright per-key RGB lighting.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "65%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      switchName: "HyperX Red",
      switchForce: "45 g",
      switchLife: "80 million keystrokes",
      keycaps: "PBT",
      caseMaterial: "Aluminum",
      software: "HyperX NGENUITY",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      onboardMemory: "Yes",
      warranty: "2 Years",
    },
    imageUrl:
      "https://row.hyperx.com/cdn/shop/products/hyperx-alloy-origins-65-1.jpg",
  },
  {
    name: "Razer BlackWidow V4 75%",
    price: 15999,
    stock: 16,
    description:
      "A customizable 75% gaming keyboard with hot-swappable switches, an aluminum top case, and per-key RGB lighting.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Tactile",
      rgb: "Yes",
      keyboardSize: "75%",
    },
    attributes: {
      pollingRate: "8000 Hz",
      hotSwappable: "Yes",
      switchName: "Razer Orange",
      switchForce: "50 g",
      keycaps: "ABS",
      mountingStyle: "Gasket Mount",
      caseMaterial: "Aluminum",
      software: "Razer Synapse",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl:
      "https://ecommerce.datablitz.com.ph/cdn/shop/files/blackwidow-v4-75-1.jpg",
  },
  {
    name: "Logitech G915 TKL Lightspeed",
    price: 18999,
    stock: 8,
    description:
      "A low-profile tenkeyless gaming keyboard featuring wireless Lightspeed connectivity, slim GL switches, and dedicated media controls.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "80% / TKL",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 40 hours",
      hotSwappable: "No",
      switchName: "GL Linear",
      keycaps: "ABS",
      caseMaterial: "Aluminum",
      connection: "Lightspeed / Bluetooth / USB",
      software: "Logitech G Hub",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl:
      "https://resource.logitech.com/content/dam/logitech/en/products/keyboards/g915-tkl/gallery/g915-tkl-black-top-view.png",
  },
  {
    name: "Keychron K8 Pro",
    price: 8999,
    stock: 29,
    description:
      "A versatile 80% mechanical keyboard offering Bluetooth and wired connectivity, hot-swappable switches, and QMK/VIA programmability.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Tactile",
      rgb: "Yes",
      keyboardSize: "80% / TKL",
    },
    attributes: {
      batteryLife: "Up to 300 hours",
      hotSwappable: "Yes",
      switchName: "Gateron G Pro Brown",
      switchForce: "55 g",
      keycaps: "PBT",
      mountingStyle: "Tray Mount",
      connection: "Bluetooth / USB-C",
      software: "QMK / VIA",
      nKeyRollover: "Yes",
      compatibility: "Windows / macOS",
      warranty: "1 Year",
    },
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0059/0630/1017/products/k8-pro-qmk-via-wireless-mechanical-keyboard.jpg",
  },
  {
    name: "Corsair K100 RGB",
    price: 21999,
    stock: 6,
    description:
      "A flagship full-size gaming keyboard with optical-mechanical switches, extensive RGB illumination, dedicated controls, and a premium aluminum frame.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Optical",
      rgb: "Yes",
      keyboardSize: "100%",
    },
    attributes: {
      pollingRate: "8000 Hz",
      switchName: "OPX Optical-Mechanical",
      switchForce: "45 g",
      switchLife: "150 million keystrokes",
      keycaps: "PBT Double-Shot",
      caseMaterial: "Aluminum",
      software: "Corsair iCUE",
      macros: "Yes",
      onboardMemory: "Yes",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl:
      "https://www.corsair.com/cdn/shop/files/K100_RGB_Mechanical_Gaming_Keyboard_1.png",
  },
  {
    name: "SteelSeries Apex 7 TKL",
    price: 10999,
    stock: 14,
    description:
      "A tenkeyless gaming keyboard with mechanical switches, per-key RGB lighting, an OLED smart display, and dedicated multimedia controls.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "80% / TKL",
    },
    attributes: {
      pollingRate: "1000 Hz",
      switchName: "SteelSeries Red",
      switchForce: "45 g",
      switchLife: "50 million keystrokes",
      keycaps: "ABS",
      caseMaterial: "Aluminum",
      software: "SteelSeries GG",
      onboardMemory: "Yes",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://i5.walmartimages.com/asr/e8071090-e7fc-4926-bc26-a78a060e77b4_1.42a521bdad46b503dc99e6f7fb2283f8.jpeg",
  },
  {
    name: "Keychron Q6 Max",
    price: 20999,
    stock: 10,
    description:
      "A full-size premium mechanical keyboard with a solid aluminum chassis, gasket-mounted construction, and flexible wired and wireless connectivity.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "100%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 180 hours",
      hotSwappable: "Yes",
      switchName: "Gateron Jupiter Red",
      keycaps: "KSA PBT",
      mountingStyle: "Gasket Mount",
      caseMaterial: "Aluminum",
      plateMaterial: "Steel",
      connection: "2.4 GHz / Bluetooth / USB-C",
      software: "Keychron Launcher",
      nKeyRollover: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0059/0630/1017/files/Q6_Max_1.jpg",
  },
  {
    name: "ASUS ROG Strix Scope II 96 Wireless",
    price: 16999,
    stock: 20,
    description:
      "A compact full-layout gaming keyboard that retains a numpad while reducing overall footprint, with wireless connectivity and hot-swappable switches.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "96%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 1500 hours",
      hotSwappable: "Yes",
      switchName: "ROG NX Snow",
      keycaps: "PBT",
      mountingStyle: "Gasket Mount",
      connection: "2.4 GHz / Bluetooth / USB-C",
      software: "Armoury Crate",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://www.wootware.co.za/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/x/9/x901-strix-scope-ii-96-8.jpg",
  },
  {
    name: "Glorious GMMK Pro",
    price: 13999,
    stock: 18,
    description:
      "A premium 75% custom mechanical keyboard with an aluminum chassis, rotary knob, hot-swappable PCB, and gasket-style mounting system.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "75%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      hotSwappable: "Yes",
      mountingStyle: "Gasket Mount",
      switchName: "Glorious Fox Linear",
      keycaps: "PBT",
      caseMaterial: "Aluminum",
      plateMaterial: "Polycarbonate",
      software: "Glorious CORE",
      nKeyRollover: "Yes",
      antiGhosting: "Yes",
      warranty: "2 Years",
    },
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0549/2681/5670/files/gmmk-pro-black.jpg",
  },
  {
    name: "NuPhy Air75 V2",
    price: 11999,
    stock: 22,
    description:
      "A slim 75% low-profile mechanical keyboard designed for portability, featuring multi-mode wireless connectivity and hot-swappable low-profile switches.",
    filters: {
      layout: "ANSI",
      connectivity: "Wired + Wireless",
      switchType: "Linear",
      rgb: "Yes",
      keyboardSize: "75%",
    },
    attributes: {
      pollingRate: "1000 Hz",
      batteryLife: "Up to 300 hours",
      hotSwappable: "Yes",
      switchName: "NuPhy Aloe Low-profile",
      keycaps: "PBT",
      caseMaterial: "Aluminum",
      connection: "2.4 GHz / Bluetooth / USB-C",
      software: "NuPhyIO",
      compatibility: "Windows / macOS",
      nKeyRollover: "Yes",
      warranty: "1 Year",
    },
    imageUrl:
      "https://cdn.shopify.com/s/files/1/0268/7299/1397/files/air75-v2-black.jpg",
  },
];

export default keyboardSeed;
