import type { Metadata } from "next";
import "../globals.css";
import { StoreProvider } from "@/providers/StoreProvider";
import NavBar from "@/components/NavBar";
import { getServerSession } from "next-auth/next";
import type { Session } from "@/types/user";
import CartView from "@/components/CartView";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await getServerSession(); // Fetch session data on the server side

  return (
    <html lang="en" className="h-full antialiased">
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <StoreProvider>
          <NavBar session={session} />
          <CartView />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
