import type { Orders } from "@/types/order";
export const fakeOrders: Orders[] = [
  {
    id: "ord_01HZX8K4M7Q2A1",
    userId: "user_001",
    status: "DELIVERED",
    originalStatus: "DELIVERED",
    paymentMethod: "CARD",
    shippingMethod: "STANDARD",
    totalAmount: 14999,
    shippingAddress: {
      id: "addr_001",
      city: "Chennai",
      phone: "9876543210",
      state: "Tamil Nadu",
      userId: "user_001",
      firstName: "Arjun",
      lastName: "Kumar",
      isDefault: true,
      postalCode: "600028",
      addressLine1: "24, Anna Salai",
      addressLine2: "Teynampet",
    },
    billingAddress: {
      id: "addr_001",
      city: "Chennai",
      phone: "9876543210",
      state: "Tamil Nadu",
      userId: "user_001",
      firstName: "Arjun",
      lastName: "Kumar",
      isDefault: true,
      postalCode: "600028",
      addressLine1: "24, Anna Salai",
      addressLine2: "Teynampet",
    },
    createdAt: "2026-08-18T10:30:00.000Z",
    updatedAt: "2026-08-21T14:20:00.000Z",
    items: [
      {
        id: "item_001",
        orderId: "ord_01HZX8K4M7Q2A1",
        productId: "prod_keyboard_01",
        quantity: 1,
        unitPrice: 14999,
        subtotal: 14999,
        product: {
          id: "prod_keyboard_01",
          name: "ASUS ROG Strix Scope II 96 Wireless",
          description:
            "A compact wireless gaming keyboard with premium switches.",
          price: 14999,
          imageUrl: "/products/rog-scope-96.jpg",
          category: "Keyboards",
          stock: 24,
          createdAt: "2026-07-01T08:00:00.000Z",
          attributes: {
            wireless: true,
            layout: "96%",
            switches: "ROG NX Snow",
          },
          slug: "asus-rog-strix-scope-ii-96-wireless",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8K9P3B7C2",
    userId: "user_002",
    status: "SHIPPED",
    originalStatus: "SHIPPED",
    paymentMethod: "CARD",
    shippingMethod: "EXPRESS",
    totalAmount: 32998,
    shippingAddress: {
      id: "addr_002",
      city: "Bengaluru",
      phone: "9123456780",
      state: "Karnataka",
      userId: "user_002",
      firstName: "Rahul",
      lastName: "Sharma",
      isDefault: true,
      postalCode: "560001",
      addressLine1: "18, MG Road",
      addressLine2: "Ashok Nagar",
    },
    billingAddress: {
      id: "addr_002",
      city: "Bengaluru",
      phone: "9123456780",
      state: "Karnataka",
      userId: "user_002",
      firstName: "Rahul",
      lastName: "Sharma",
      isDefault: true,
      postalCode: "560001",
      addressLine1: "18, MG Road",
      addressLine2: "Ashok Nagar",
    },
    createdAt: "2026-08-22T09:15:00.000Z",
    updatedAt: "2026-08-24T12:10:00.000Z",
    items: [
      {
        id: "item_002",
        orderId: "ord_01HZX8K9P3B7C2",
        productId: "prod_mouse_01",
        quantity: 1,
        unitPrice: 7999,
        subtotal: 7999,
        product: {
          id: "prod_mouse_01",
          name: "Logitech G Pro X Superlight 2",
          description: "High-performance lightweight wireless gaming mouse.",
          price: 7999,
          imageUrl: "/products/g-pro-x-superlight-2.jpg",
          category: "Mice",
          stock: 31,
          createdAt: "2026-07-05T08:00:00.000Z",
          attributes: {
            wireless: true,
            weight: "60g",
            sensor: "HERO 2",
          },
          slug: "logitech-g-pro-x-superlight-2",
          isActive: true,
        },
      },
      {
        id: "item_003",
        orderId: "ord_01HZX8K9P3B7C2",
        productId: "prod_headset_01",
        quantity: 1,
        unitPrice: 24999,
        subtotal: 24999,
        product: {
          id: "prod_headset_01",
          name: "SteelSeries Arctis Nova Pro Wireless",
          description:
            "Premium wireless gaming headset with active noise cancellation.",
          price: 24999,
          imageUrl: "/products/arctis-nova-pro.jpg",
          category: "Headsets",
          stock: 12,
          createdAt: "2026-06-28T08:00:00.000Z",
          attributes: {
            wireless: true,
            anc: true,
            surround: "360 Spatial Audio",
          },
          slug: "steelseries-arctis-nova-pro-wireless",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8KF8D4E3",
    userId: "user_003",
    status: "PENDING",
    originalStatus: "PENDING",
    paymentMethod: "CARD",
    shippingMethod: "STANDARD",
    totalAmount: 45999,
    shippingAddress: {
      id: "addr_003",
      city: "Hyderabad",
      phone: "9988776655",
      state: "Telangana",
      userId: "user_003",
      firstName: "Vikram",
      lastName: "Reddy",
      isDefault: true,
      postalCode: "500034",
      addressLine1: "12, Road No. 36",
      addressLine2: "Jubilee Hills",
    },
    billingAddress: {
      id: "addr_003",
      city: "Hyderabad",
      phone: "9988776655",
      state: "Telangana",
      userId: "user_003",
      firstName: "Vikram",
      lastName: "Reddy",
      isDefault: true,
      postalCode: "500034",
      addressLine1: "12, Road No. 36",
      addressLine2: "Jubilee Hills",
    },
    createdAt: "2026-08-25T11:45:00.000Z",
    updatedAt: "2026-08-25T13:00:00.000Z",
    items: [
      {
        id: "item_004",
        orderId: "ord_01HZX8KF8D4E3",
        productId: "prod_monitor_01",
        quantity: 1,
        unitPrice: 45999,
        subtotal: 45999,
        product: {
          id: "prod_monitor_01",
          name: "LG UltraGear 27GR95QE",
          description:
            "27-inch QHD OLED gaming monitor with a 240Hz refresh rate.",
          price: 45999,
          imageUrl: "/products/lg-ultragear-27gr95qe.jpg",
          category: "Monitors",
          stock: 8,
          createdAt: "2026-06-15T08:00:00.000Z",
          attributes: {
            resolution: "2560x1440",
            refreshRate: 240,
            panel: "OLED",
            size: "27-inch",
          },
          slug: "lg-ultragear-27gr95qe",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8KQ5F9G4",
    userId: "user_004",
    status: "PENDING",
    originalStatus: "PENDING",
    paymentMethod: "CARD",
    shippingMethod: "STANDARD",
    totalAmount: 12998,
    shippingAddress: {
      id: "addr_004",
      city: "Mumbai",
      phone: "9090909090",
      state: "Maharashtra",
      userId: "user_004",
      firstName: "Neha",
      lastName: "Patel",
      isDefault: true,
      postalCode: "400050",
      addressLine1: "45, Linking Road",
      addressLine2: "Bandra West",
    },
    billingAddress: {
      id: "addr_004",
      city: "Mumbai",
      phone: "9090909090",
      state: "Maharashtra",
      userId: "user_004",
      firstName: "Neha",
      lastName: "Patel",
      isDefault: true,
      postalCode: "400050",
      addressLine1: "45, Linking Road",
      addressLine2: "Bandra West",
    },
    createdAt: "2026-08-26T06:20:00.000Z",
    updatedAt: "2026-08-26T06:20:00.000Z",
    items: [
      {
        id: "item_005",
        orderId: "ord_01HZX8KQ5F9G4",
        productId: "prod_keyboard_02",
        quantity: 1,
        unitPrice: 12998,
        subtotal: 12998,
        product: {
          id: "prod_keyboard_02",
          name: "Keychron Q1 Pro",
          description:
            "Premium aluminum mechanical keyboard with wireless connectivity.",
          price: 12998,
          imageUrl: "/products/keychron-q1-pro.jpg",
          category: "Keyboards",
          stock: 17,
          createdAt: "2026-05-20T08:00:00.000Z",
          attributes: {
            wireless: true,
            layout: "75%",
            switches: "Gateron Jupiter",
          },
          slug: "keychron-q1-pro",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8KW2J6K5",
    userId: "user_005",
    status: "CANCELLED",
    originalStatus: "CANCELLED",
    paymentMethod: "CARD",
    shippingMethod: "STANDARD",
    totalAmount: 8999,
    shippingAddress: {
      id: "addr_005",
      city: "Pune",
      phone: "9876501234",
      state: "Maharashtra",
      userId: "user_005",
      firstName: "Aditya",
      lastName: "Joshi",
      isDefault: true,
      postalCode: "411001",
      addressLine1: "8, FC Road",
      addressLine2: "Shivajinagar",
    },
    billingAddress: {
      id: "addr_005",
      city: "Pune",
      phone: "9876501234",
      state: "Maharashtra",
      userId: "user_005",
      firstName: "Aditya",
      lastName: "Joshi",
      isDefault: true,
      postalCode: "411001",
      addressLine1: "8, FC Road",
      addressLine2: "Shivajinagar",
    },
    createdAt: "2026-08-20T15:40:00.000Z",
    updatedAt: "2026-08-21T08:30:00.000Z",
    items: [
      {
        id: "item_006",
        orderId: "ord_01HZX8KW2J6K5",
        productId: "prod_mouse_02",
        quantity: 1,
        unitPrice: 8999,
        subtotal: 8999,
        product: {
          id: "prod_mouse_02",
          name: "Razer DeathAdder V3 Pro",
          description: "Ergonomic lightweight wireless gaming mouse.",
          price: 8999,
          imageUrl: "/products/deathadder-v3-pro.jpg",
          category: "Mice",
          stock: 19,
          createdAt: "2026-06-10T08:00:00.000Z",
          attributes: {
            wireless: true,
            weight: "63g",
            sensor: "Focus Pro 30K",
          },
          slug: "razer-deathadder-v3-pro",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8L3M8N6P",
    userId: "user_006",
    status: "DELIVERED",
    originalStatus: "DELIVERED",
    paymentMethod: "CARD",
    shippingMethod: "STANDARD",
    totalAmount: 61997,
    shippingAddress: {
      id: "addr_006",
      city: "Delhi",
      phone: "9811122233",
      state: "Delhi",
      userId: "user_006",
      firstName: "Karan",
      lastName: "Mehta",
      isDefault: true,
      postalCode: "110017",
      addressLine1: "32, Saket",
      addressLine2: "Malviya Nagar",
    },
    billingAddress: {
      id: "addr_006",
      city: "Delhi",
      phone: "9811122233",
      state: "Delhi",
      userId: "user_006",
      firstName: "Karan",
      lastName: "Mehta",
      isDefault: true,
      postalCode: "110017",
      addressLine1: "32, Saket",
      addressLine2: "Malviya Nagar",
    },
    createdAt: "2026-08-10T12:00:00.000Z",
    updatedAt: "2026-08-15T16:30:00.000Z",
    items: [
      {
        id: "item_007",
        orderId: "ord_01HZX8L3M8N6P",
        productId: "prod_monitor_02",
        quantity: 1,
        unitPrice: 39999,
        subtotal: 39999,
        product: {
          id: "prod_monitor_02",
          name: "Samsung Odyssey G7",
          description: "High-refresh-rate curved QHD gaming monitor.",
          price: 39999,
          imageUrl: "/products/samsung-odyssey-g7.jpg",
          category: "Monitors",
          stock: 14,
          createdAt: "2026-05-12T08:00:00.000Z",
          attributes: {
            resolution: "2560x1440",
            refreshRate: 240,
            panel: "VA",
            size: "32-inch",
          },
          slug: "samsung-odyssey-g7",
          isActive: true,
        },
      },
      {
        id: "item_008",
        orderId: "ord_01HZX8L3M8N6P",
        productId: "prod_mouse_03",
        quantity: 1,
        unitPrice: 21998,
        subtotal: 21998,
        product: {
          id: "prod_mouse_03",
          name: "Finalmouse UltralightX",
          description: "Ultra-lightweight enthusiast gaming mouse.",
          price: 21998,
          imageUrl: "/products/finalmouse-ulx.jpg",
          category: "Mice",
          stock: 6,
          createdAt: "2026-04-20T08:00:00.000Z",
          attributes: {
            wireless: true,
            weight: "38g",
            sensor: "PAW3395",
          },
          slug: "finalmouse-ultralightx",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8L9Q1R7S",
    userId: "user_007",
    status: "DELIVERED",
    originalStatus: "DELIVERED",
    paymentMethod: "CARD",
    shippingMethod: "EXPRESS",
    totalAmount: 18999,
    shippingAddress: {
      id: "addr_007",
      city: "Kochi",
      phone: "9447001122",
      state: "Kerala",
      userId: "user_007",
      firstName: "Arun",
      lastName: "Nair",
      isDefault: true,
      postalCode: "682016",
      addressLine1: "15, MG Road",
      addressLine2: "Ernakulam",
    },
    billingAddress: {
      id: "addr_007",
      city: "Kochi",
      phone: "9447001122",
      state: "Kerala",
      userId: "user_007",
      firstName: "Arun",
      lastName: "Nair",
      isDefault: true,
      postalCode: "682016",
      addressLine1: "15, MG Road",
      addressLine2: "Ernakulam",
    },
    createdAt: "2026-08-23T10:10:00.000Z",
    updatedAt: "2026-08-26T07:45:00.000Z",
    items: [
      {
        id: "item_009",
        orderId: "ord_01HZX8L9Q1R7S",
        productId: "prod_headset_02",
        quantity: 1,
        unitPrice: 18999,
        subtotal: 18999,
        product: {
          id: "prod_headset_02",
          name: "HyperX Cloud III Wireless",
          description:
            "Comfortable wireless gaming headset with long battery life.",
          price: 18999,
          imageUrl: "/products/hyperx-cloud-iii.jpg",
          category: "Headsets",
          stock: 27,
          createdAt: "2026-06-22T08:00:00.000Z",
          attributes: {
            wireless: true,
            batteryLife: "120 hours",
            surround: "DTS Headphone:X",
          },
          slug: "hyperx-cloud-iii-wireless",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8LF4T8U9",
    userId: "user_008",
    status: "DELIVERED",
    originalStatus: "DELIVERED",
    paymentMethod: "CARD",
    shippingMethod: "STANDARD",
    totalAmount: 27996,
    shippingAddress: {
      id: "addr_008",
      city: "Ahmedabad",
      phone: "9898989898",
      state: "Gujarat",
      userId: "user_008",
      firstName: "Rohan",
      lastName: "Shah",
      isDefault: true,
      postalCode: "380009",
      addressLine1: "21, CG Road",
      addressLine2: "Navrangpura",
    },
    billingAddress: {
      id: "addr_008",
      city: "Ahmedabad",
      phone: "9898989898",
      state: "Gujarat",
      userId: "user_008",
      firstName: "Rohan",
      lastName: "Shah",
      isDefault: true,
      postalCode: "380009",
      addressLine1: "21, CG Road",
      addressLine2: "Navrangpura",
    },
    createdAt: "2026-08-24T16:25:00.000Z",
    updatedAt: "2026-08-25T09:15:00.000Z",
    items: [
      {
        id: "item_010",
        orderId: "ord_01HZX8LF4T8U9",
        productId: "prod_keyboard_03",
        quantity: 2,
        unitPrice: 13998,
        subtotal: 27996,
        product: {
          id: "prod_keyboard_03",
          name: "SteelSeries Apex Pro TKL Wireless",
          description:
            "Wireless gaming keyboard with adjustable mechanical switches.",
          price: 13998,
          imageUrl: "/products/apex-pro-tkl.jpg",
          category: "Keyboards",
          stock: 9,
          createdAt: "2026-05-30T08:00:00.000Z",
          attributes: {
            wireless: true,
            layout: "TKL",
            switches: "OmniPoint 2.0",
          },
          slug: "steelseries-apex-pro-tkl-wireless",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8LKM2V0W",
    userId: "user_009",
    status: "DELIVERED",
    originalStatus: "DELIVERED",
    paymentMethod: "CARD",
    shippingMethod: "STANDARD",
    totalAmount: 54997,
    shippingAddress: {
      id: "addr_009",
      city: "Jaipur",
      phone: "9797979797",
      state: "Rajasthan",
      userId: "user_009",
      firstName: "Siddharth",
      lastName: "Singh",
      isDefault: true,
      postalCode: "302001",
      addressLine1: "7, MI Road",
      addressLine2: "C-Scheme",
    },
    billingAddress: {
      id: "addr_009",
      city: "Jaipur",
      phone: "9797979797",
      state: "Rajasthan",
      userId: "user_009",
      firstName: "Siddharth",
      lastName: "Singh",
      isDefault: true,
      postalCode: "302001",
      addressLine1: "7, MI Road",
      addressLine2: "C-Scheme",
    },
    createdAt: "2026-08-05T09:00:00.000Z",
    updatedAt: "2026-08-10T15:20:00.000Z",
    items: [
      {
        id: "item_011",
        orderId: "ord_01HZX8LKM2V0W",
        productId: "prod_monitor_03",
        quantity: 1,
        unitPrice: 54997,
        subtotal: 54997,
        product: {
          id: "prod_monitor_03",
          name: "Alienware AW3423DWF",
          description: "34-inch ultrawide QD-OLED gaming monitor.",
          price: 54997,
          imageUrl: "/products/alienware-aw3423dwf.jpg",
          category: "Monitors",
          stock: 5,
          createdAt: "2026-04-18T08:00:00.000Z",
          attributes: {
            resolution: "3440x1440",
            refreshRate: 165,
            panel: "QD-OLED",
            size: "34-inch",
          },
          slug: "alienware-aw3423dwf",
          isActive: true,
        },
      },
    ],
  },

  {
    id: "ord_01HZX8LQ6X1Y2",
    userId: "user_010",
    status: "SHIPPED",
    originalStatus: "SHIPPED",
    paymentMethod: "CARD",
    shippingMethod: "EXPRESS",
    totalAmount: 23997,
    shippingAddress: {
      id: "addr_010",
      city: "Chennai",
      phone: "9000012345",
      state: "Tamil Nadu",
      userId: "user_010",
      firstName: "Pranav",
      lastName: "Iyer",
      isDefault: true,
      postalCode: "600034",
      addressLine1: "10, Cathedral Road",
      addressLine2: "Nungambakkam",
    },
    billingAddress: {
      id: "addr_010",
      city: "Chennai",
      phone: "9000012345",
      state: "Tamil Nadu",
      userId: "user_010",
      firstName: "Pranav",
      lastName: "Iyer",
      isDefault: true,
      postalCode: "600034",
      addressLine1: "10, Cathedral Road",
      addressLine2: "Nungambakkam",
    },
    createdAt: "2026-08-21T13:30:00.000Z",
    updatedAt: "2026-08-23T10:40:00.000Z",
    items: [
      {
        id: "item_012",
        orderId: "ord_01HZX8LQ6X1Y2",
        productId: "prod_keyboard_04",
        quantity: 1,
        unitPrice: 10999,
        subtotal: 10999,
        product: {
          id: "prod_keyboard_04",
          name: "Wooting 80HE",
          description:
            "Hall-effect gaming keyboard with rapid trigger technology.",
          price: 10999,
          imageUrl: "/products/wooting-80he.jpg",
          category: "Keyboards",
          stock: 11,
          createdAt: "2026-06-01T08:00:00.000Z",
          attributes: {
            rapidTrigger: true,
            layout: "80%",
            switches: "Lekker V2",
          },
          slug: "wooting-80he",
          isActive: true,
        },
      },
      {
        id: "item_013",
        orderId: "ord_01HZX8LQ6X1Y2",
        productId: "prod_mouse_04",
        quantity: 1,
        unitPrice: 12998,
        subtotal: 12998,
        product: {
          id: "prod_mouse_04",
          name: "Razer Viper V3 Pro",
          description: "Ultra-lightweight esports wireless gaming mouse.",
          price: 12998,
          imageUrl: "/products/razer-viper-v3-pro.jpg",
          category: "Mice",
          stock: 22,
          createdAt: "2026-06-05T08:00:00.000Z",
          attributes: {
            wireless: true,
            weight: "54g",
            sensor: "Focus Pro 35K",
          },
          slug: "razer-viper-v3-pro",
          isActive: true,
        },
      },
    ],
  },
];
